### PR TITLE
Fix preview

### LINKED ISSUE #152: [Fix Preview] Presentation Module - Feed screen not visible
**Describe the bug**
In the presentation Module, one can't see a preview of the Feed screen in the IDE

**To Reproduce**
Refer to the screenshot below.

**Expected behavior**
A preview of the feed screen in the IDE

**Screenshots**
Screenshot 2023-07-25 at 15 30 01

### PR DESCRIPTION
**Pull request by yveskalume**
# Scope

_Please make sure to read the [Contribution Guidelines](https://github.com/droidconKE/droidconKE2023Android/blob/main/CONTRIBUTING.md)
and check that you understand and have followed it as best as possible Explain what your feature
does in a short paragraph._ please check the below boxes
- [x] I have followed the coding conventions
- [x] I have added/updated necessary tests
- [x] I have tested the changes added on a physical device
- [x] I have run `./codeAnalysis.sh` on linux/unix or `codeAnalysys.bat` on windows to make sure all lint/formatting checks have been done.

## Closes/Fixes Issues
fixes #152 

## Other testing QA Notes
_What have you tested specifically and what possible impacts/areas there are that may need retesting
by others._

### CODE REVIEW

**Review by wangerekaharun — APPROVED** [review]
Looks good, @yveskalume one request, can you add some explanation on the readme to explain the approach and why ti works

**Comment by yveskalume** [comment]
@wangerekaharun should I create a new section on the Readme.md ?

**Comment by wangerekaharun** [comment]
> @wangerekaharun should I create a new section on the Readme.md ?

Yes

**Comment by yveskalume** [comment]
Done @wangerekaharun

**Comment by wangerekaharun** [comment]
> Done @wangerekaharun

Looks good

**Review by chepsi — APPROVED** [review]

**Pull request merged**
