### PR TITLE
Feed offline first

### PR DESCRIPTION
**Pull request by chege4179**
Added offline first capabilities to the feed feature

### CODE REVIEW

**Review by wangerekaharun — APPROVED** [review]

**Comment by wangerekaharun** [comment]
@chege4179 this looks good, please rebase

**Comment by wangerekaharun** [comment]
@chege4179 one last thing, the data sources were moved to a separate module, can you move these new ones too?

**Comment by chepsi** [comment]
@wangerekaharun we can tackle this in a separate pr.

**Comment by wangerekaharun** [comment]
> @wangerekaharun we can tackle this in a separate PR.

Got it, @chege4179 ignore my comment😀

**Comment by chege4179** [comment]
Should I do it or should I leave @chepsi  to handle it  ?

**Comment by chepsi** [comment]
@chege4179 leave it we can tackle it in a separate PR

**Review by chepsi — APPROVED** [review]

**Comment by chege4179** [comment]
@wangerekaharun  @chepsi Is there anything left for this PR ??

**Comment by chepsi** [comment]
@chege4179 no... Let me merge it. Great job 🏅

**Comment by chepsi** [comment]
@chege4179 there seems to be a conflict with the base branch. do you mind rebasing?

**Comment by chege4179** [comment]
Try now

**Comment by chege4179** [comment]
In the checks it saying there's no conflicts with the base branch yet the merge bot says there are ....so I'm confused

**Comment by chepsi** [comment]
@chege4179 I can check it out in the morning

**Comment by chege4179** [comment]
ok no problem

**Comment by chepsi** [comment]
Hey @chege4179 check this out on how to [sync a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

**Comment by chege4179** [comment]
@chepsi tried both options and my fork is already up to date

**Pull request merged**
